{% set name = "ptm_pose" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ptm_pose-{{ version }}.tar.gz
  sha256: 15df86118e85bd7231595f6420071ab4fb47ad38912654264cb698b7d4fc3ce2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - pandas >=2.2
    - numpy >=1.26
    - biopython >=1.78
    - tqdm >=4.66
    - scipy >=1.13
    - xlrd
    - matplotlib-base
    - seaborn
    - requests

test:
  imports:
    - ptm_pose
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NaegleLab/PTM-POSE/tree/main
  summary: 'PTM-POSE: PTM Projection onto Splice Events'
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srcrowl
